version: 2.1

jobs:
  test-and-lint:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - run:
          name: lint
          command: flake8 --config=setup.cfg
      - run:
          name: run tests
          command: pytest

  build-and-push-to-dockerhub:
    docker:
      - image: cimg/go:1.17
        # environment:
        #   DJANGO_ALLOWED_HOSTS: $DJANGO_ALLOWED_HOSTS
        #   DJANGO_DEBUG: $DJANGO_DEBUG
        #   DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true

      - run:
          command: |
            echo $DJANGO_ALLOWED_HOSTS
            echo $DJANGO_DEBUG
            echo $DJANGO_SECRET_KEY

      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t philpjsdev/p13_test:$TAG
          --build-arg DJANGO_ALLOWED_HOSTS=echo $DJANGO_ALLOWED_HOSTS
          --build-arg DJANGO_DEBUG=echo $DJANGO_DEBUG
          --build-arg DJANGO_SECRET_KEY=echo $DJANGO_SECRET_KEY 
          .
          echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
          docker push philpjsdev/p13_test:$TAG


orbs:
  heroku: circleci/heroku@1.2.6



workflows:
  build-test-deploy-workflow:
    jobs:
      - test-and-lint

      - build-and-push-to-dockerhub:
          filters:
            branches:
              only:
                - main
          requires:
            - test-and-lint

      - heroku/deploy-via-git:
          filters:
            branches:
              only:
                - main
          requires:
            - build-and-push-to-dockerhub
