version: 2.1

jobs:
  test-and-lint:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - run:
          name: lint
          command: flake8 --config=setup.cfg
      - run:
          name: run tests
          command: pytest



orbs:
  heroku: circleci/heroku@1.2.6



workflows:
  build-and-test-workflow:
    jobs:
      - test-and-lint
          # filters:
          #   branches:
          #     ignore:
          #       - main
      
  
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git:
          filters:
            branches:
              only:
                - main

# workflows:
#   test-and-lint-workflow:
#     jobs:
#       - test-and-lint:
#           filters:
#               branches:
#                 ignore:
#                   - main
#                 # only:
#                 #   - dev